//@version=6
// Debug only floats, no ints
indicator("Debug Only Floats", shorttitle="DebugOnlyFloats", overlay=true)

floatCount1 = 0.0
floatCount2 = 0.0

for i = 0 to 4
    floatCount1 := floatCount1 + 1.0
    floatCount2 := floatCount2 + 1.0
    dummy = close[i]

plot(floatCount1, title="floatCount1", color=color.red, display=display.none)
plot(floatCount2, title="floatCount2", color=color.green, display=display.none)
