//@version=6
// Debug order of assignments
indicator("Debug Order 2", shorttitle="DebugOrder2", overlay=true)

floatCount = 0.0
sum = 0.0
intCount = 0

for i = 0 to 4
    sum := sum + close[i]
    floatCount := floatCount + 1.0
    intCount := intCount + 1

plot(intCount, title="intCount", color=color.red, display=display.none)
plot(floatCount, title="floatCount", color=color.green, display=display.none)
plot(sum, title="sum", color=color.blue, display=display.none)
